kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-pdl-produsent-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: pdl-produsent
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: kodeverk-api.nav.no
        - host: pdl-mottak.dev-fss-pub.nais.io
        - host: dev-gcp.eessibasis.eux-rina-api-q2
        - host: norg2.dev-fss-pub.nais.io
        - host: saf-q2.dev-fss-pub.nais.io
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: NAMESPACE
      value: q2
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q2.preprod.local/SecurityTokenServiceProvider/
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-eessibasis.eux-rina-api-q2/cpi
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_MOTTAK_URL
      value: https://pdl-mottak.dev-fss-pub.nais.io
    - name: NORG2_URL
      value: https://norg2.dev-fss-pub.nais.io/norg2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1-q2
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave-q2
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: dev-fss.eessipensjon.eessi-pensjon-onprem-proxy-q2
    - name: AZURE_APP_KODEVERK_CLIENT_ID
      value: kodeverk-api.nav.no
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-gcp.eessibasis.eux-rina-api-q2
    - name: AZURE_APP_NORG2_CLIENT_ID
      value: dev-fss.org.norg2
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: AZURE_APP_PDL_MOTTAK_CLIENT_ID
      value: dev-fss.pdl.pdl-mottak
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-pdl-produsent-dev-q2
    - name: AZURE_APP_SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf
    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: SAF_HENTDOKUMENT_URL
      value: https://saf-q2.dev-fss-pub.nais.io/rest/hentdokument

  gcp:
    buckets:
      - name: eessi-pensjon-pdl-produsent-dev-q2
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-pdl-produsent-q2.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi