kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-pdl-produsent
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: pdl-produsent
  azure:
    application:
      enabled: true
    accessPolicy:
      outbound:
        external:
          - host: https://eessi-pensjon-pdl-produsent.intern.nav.no
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api.prod-fss-pub.nais.io/cpi
    - name: AZURE_APP_EUX_CLIENT_ID
      value: prod-fss.eessibasis.eux-rina-api
    - name: AZURE_APP_PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: dev-fss.eessipensjon.eessi-pensjon-onprem-proxy-q2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1-q2
    - name: NORG2_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io/api/v1/arbeidsfordeling
    - name: KODEVERK_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io/
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-pdl-produsent-dev

  gcp:
    buckets:
      - name: eessi-pensjon-pdl-produsent-dev
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-pdl-produsent.nais.adeo.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 4096Mi
    requests:
      cpu: 400m
      memory: 1024Mi