kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-pdl-produsent
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  envFrom:
    - secret: pdl-produsent-prod
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kodeverk-api.nav.no
        - host: eux-rina-api.intern.nav.no
        - host: norg2.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: pdl-mottak.prod-fss-pub.nais.io
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: NAMESPACE
      value: p

    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api.intern.nav.no/cpi
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_MOTTAK_URL
      value: https://pdl-mottak.prod-fss-pub.nais.io
    - name: NORG2_URL
      value: https://norg2.prod-fss-pub.nais.io/norg2
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: SAF_GRAPHQL_URL
      value: https://saf.prod-fss-pub.nais.io/graphql
    - name: SAF_HENTDOKUMENT_URL
      value: https://saf.prod-fss-pub.nais.io/rest/hentdokument

    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave

    - name: AZURE_APP_PROXY_CLIENT_ID
      value: prod-fss.eessipensjon.eessi-pensjon-onprem-proxy
    - name: AZURE_APP_KODEVERK_CLIENT_ID
      value: prod-gcp.team-rocket.kodeverk-api
    - name: AZURE_APP_EUX_CLIENT_ID
      value: prod-gcp.eessibasis.eux-rina-api
    - name: AZURE_APP_NORG2_CLIENT_ID
      value: prod-fss.org.norg2
    - name: AZURE_APP_PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: AZURE_APP_PDL_MOTTAK_CLIENT_ID
      value: prod-fss.pdl.pdl-mottak
    - name: AZURE_APP_SAF_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.saf

    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-pdl-produsent-prod

  gcp:
    buckets:
      - name: eessi-pensjon-pdl-produsent-prod
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-pdl-produsent.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 75m
      memory: 700Mi