kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-pdl-produsent
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: NAMESPACE
      value: p
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api.nais.adeo.no/cpi
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: OPPGAVE_OPPGAVER_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: NORG2_URL
      value: https://app.adeo.no/norg2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-pdl-produsent.nais.adeo.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{serviceuserkv}}
        mountPath: /var/run/secrets/nais.io/srveessipensjonpdlp
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault

