kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-pdl-produsent
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  envFrom:
    - secret: pdl-produsent-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: https://eessi-pensjon-pdl-produsent.intern.nav.no
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: NAMESPACE
      value: p
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api.prod-fss-pub.nais.io/cpi
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: NORG2_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io/api/v1/arbeidsfordeling
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessibasis.sedmottatt-v1
    - name: KAFKA_OPPGAVE_TOPIC
      value: eessipensjon.privat-oppgave
    - name: KODEVERK_REST_API_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy.prod-fss-pub.nais.io
    - name: AZURE_APP_EUX_CLIENT_ID
      value: prod-fss.eessibasis.eux-rina-api
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: prod-fss.eessipensjon.eessi-pensjon-onprem-proxy
    - name: AZURE_APP_PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-pdl-produsent-prod

  gcp:
    buckets:
      - name: eessi-pensjon-pdl-produsent-prod
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-pdl-produsent.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi